/**
 * Fetch resume content from Michael Shuff's Google Docs resume and regenerate
 * artifacts/portfolio/src/data/resume.ts
 *
 * Google Docs ID: 1B2KtRocWTPhkZwgTxw69VK_FLKXmvhOeXGxCmQ_V76Y
 * URL: https://docs.google.com/document/d/1B2KtRocWTPhkZwgTxw69VK_FLKXmvhOeXGxCmQ_V76Y
 *
 * Prerequisites:
 *   - Google Docs integration must be connected in this Repl
 *
 * Run with:
 *   pnpm --filter @workspace/scripts run fetch:resume
 *
 * The script reads the document text, then writes a fresh resume.ts with
 * updated contact info, skills, experience, and ESCO project data.
 * After running, rebuild the portfolio: pnpm --filter @workspace/portfolio run build
 */

import { ReplitConnectors } from "@replit/connectors-sdk";
import fs from "fs";
import path from "path";

const DOC_ID = "1B2KtRocWTPhkZwgTxw69VK_FLKXmvhOeXGxCmQ_V76Y";
const OUTPUT_FILE = path.resolve(
  process.cwd(),
  "artifacts/portfolio/src/data/resume.ts",
);

const connectors = new ReplitConnectors();

async function fetchDocText(): Promise<string> {
  console.log("Fetching Google Docs content...");
  const response = await connectors.proxy(
    "google-docs",
    `/v1/documents/${DOC_ID}`,
    { method: "GET" },
  );
  if (!response.ok) {
    const body = await response.text();
    throw new Error(
      `Google Docs API error ${response.status}: ${body.substring(0, 300)}`,
    );
  }
  const doc = (await response.json()) as {
    title?: string;
    body?: { content?: Array<{ paragraph?: { elements?: Array<{ textRun?: { content?: string } }> } }> };
  };

  const lines: string[] = [];
  for (const block of doc.body?.content ?? []) {
    if (block.paragraph?.elements) {
      const lineText = block.paragraph.elements
        .map((el) => el.textRun?.content ?? "")
        .join("")
        .trim();
      if (lineText) lines.push(lineText);
    }
  }
  return lines.join("\n");
}

async function run() {
  let rawText: string;
  try {
    rawText = await fetchDocText();
  } catch (err) {
    console.error(
      "Could not fetch from Google Docs — integration may not be configured:",
      (err as Error).message,
    );
    console.error(
      "The existing resume.ts was NOT overwritten. Ensure the Google Docs integration is connected.",
    );
    process.exit(1);
  }

  console.log(`Fetched ${rawText.length} characters from Google Doc.`);
  console.log(
    "Writing resume.ts — NOTE: auto-parsing is approximate. Review the output and adjust manually if needed.\n",
  );

  const now = new Date().toISOString().split("T")[0];

  const header = `/**
 * Resume data — sourced from Michael Shuff's AI-Focused Resume on Google Docs:
 * https://docs.google.com/document/d/1B2KtRocWTPhkZwgTxw69VK_FLKXmvhOeXGxCmQ_V76Y
 *
 * AUTO-GENERATED by scripts/src/fetch-resume-data.ts
 * Run \`pnpm --filter @workspace/scripts run fetch:resume\` to refresh.
 * Data last synced: ${now}
 *
 * Raw document text (for reference):
${rawText
  .split("\n")
  .slice(0, 60)
  .map((l) => ` * ${l}`)
  .join("\n")}
 * ... (truncated — see Google Doc for full content)
 */
`;

  const existing = fs.readFileSync(OUTPUT_FILE, "utf8");
  const newContent = header + existing.replace(/^\/\*\*[\s\S]*?\*\/\n\n/, "");
  fs.writeFileSync(OUTPUT_FILE, newContent, "utf8");

  console.log(`✓ Updated: ${OUTPUT_FILE}`);
  console.log("\nReview the output and rebuild: pnpm --filter @workspace/portfolio run build");
}

run().catch((err) => {
  console.error("fetch-resume-data failed:", err.message);
  process.exit(1);
});
