/**
 * Resume data — sourced from Michael Shuff's AI-Focused Resume on Google Docs:
 * https://docs.google.com/document/d/1B2KtRocWTPhkZwgTxw69VK_FLKXmvhOeXGxCmQ_V76Y
 *
 * Dynamic content (personal info, bio, skills, experience) is imported from
 * resume.json, which is generated by running:
 *   pnpm --filter @workspace/scripts run fetch:resume
 *
 * Static content (ESCO project details, Figma board links, ecosystem projects)
 * is maintained here as it is not in the Google Doc.
 *
 * resume.json last synced: see the `lastSynced` field in that file.
 */

import resumeJson from "./resume.json";

export const PERSONAL = resumeJson.personal;

export const ABOUT = {
  bio: resumeJson.about.bio,
  stats: resumeJson.about.stats,
};

export const SKILLS = resumeJson.skills.length > 0
  ? resumeJson.skills
  : [
      { title: "AI & Research", skills: [{ name: "LLM APIs", level: 4 }, { name: "Prompt Engineering", level: 5 }, { name: "Ethical AI Systems", level: 5 }, { name: "Adversarial Testing", level: 4 }, { name: "Neuro-Symbolic Logic", level: 4 }, { name: "Fallacy Detection", level: 4 }] },
      { title: "Languages", skills: [{ name: "JavaScript (ES6+)", level: 5 }, { name: "TypeScript", level: 5 }, { name: "C", level: 4 }, { name: "Python", level: 4 }, { name: "SQL", level: 4 }, { name: "HTML/CSS", level: 5 }] },
      { title: "Frontend", skills: [{ name: "React", level: 5 }, { name: "Next.js", level: 4 }, { name: "Redux", level: 4 }, { name: "Tailwind CSS", level: 4 }, { name: "Material-UI", level: 3 }] },
      { title: "Backend & Data", skills: [{ name: "Node.js", level: 4 }, { name: "NestJS", level: 3 }, { name: "Express", level: 4 }, { name: "GraphQL", level: 3 }, { name: "PostgreSQL", level: 4 }] },
      { title: "Infrastructure", skills: [{ name: "Docker", level: 3 }, { name: "AWS (CloudFormation, Lambda, S3)", level: 4 }, { name: "GitHub Actions", level: 4 }, { name: "CI/CD", level: 4 }] },
      { title: "Testing & Methods", skills: [{ name: "Cypress", level: 4 }, { name: "Jest", level: 4 }, { name: "TDD", level: 4 }, { name: "Agile/Scrum", level: 4 }, { name: "Systems Architecture", level: 4 }] },
    ];

export const EXPERIENCE = resumeJson.experience.length > 0
  ? resumeJson.experience.filter(e => e.company && e.bullets.length >= 2)
  : [
      {
        title: "IC2 Software Engineer",
        company: "Constructor.io",
        date: "Dec 2022 – Nov 2025",
        bullets: [
          "Built real-time fitment POC that closed RealTruck (5× Algolia's rate) after a 7-month evaluation",
          "Fitment system foundational in $30M+ ARR conversion pipeline (CarParts, Classic Industries)",
          "Created Constructor's first B2B sandbox with fitment, reused across multiple verticals",
          "Lead Technical Architect for first Hebrew/RTL search integration in Israel (Super-Pharm)",
          "Bridged visibility gaps between engineering effort and revenue attribution",
        ],
      },
      {
        title: "Associate Software Engineer / CRE",
        company: "Vault Health",
        date: "Mar 2022 – Sept 2022",
        bullets: [
          "Deployed DevOps SOPs for monitoring and prioritizing escalation tickets across all engineering teams",
          "Monitored AWS Lambdas, SQS Queues, S3 via CloudWatch Log Groups to ensure system high availability",
          "Designed clinical research platform using Next.js, TypeScript, Redux Toolkit, and Material-UI",
          "Automated full end-to-end testing with Jest and Cypress",
        ],
      },
      {
        title: "Technical Career Coach & Instructional Assistant",
        company: "App Academy",
        date: "Jan 2021 – Feb 2022",
        bullets: [
          "Mentored 75+ graduates through technical interviews and DS&A whiteboarding",
          "Taught 70+ students ES6, OOP, and scalable full-stack development curriculum",
          "Reviewed hundreds of monthly projects, providing feedback on system design and debugging complex logic",
        ],
      },
      {
        title: "Electronics Technician",
        company: "U.S. Navy",
        date: "2001 – 2006",
        bullets: [
          "Maintained and troubleshot mission-critical shipboard electronics and communications systems under high-stakes operational conditions, where failure was not an option.",
          "Diagnosed complex system failures in time-pressured environments, developing a disciplined fault-isolation methodology that translates directly to debugging distributed software systems.",
          "Operated and serviced mission-critical navigation, radar, and communications equipment demanding zero-downtime reliability standards.",
          "Cultivated rigorous attention to detail, procedural discipline, and composure under pressure — principles that underpin a career-long engineering standard of mission-critical reliability.",
        ],
      },
    ];

export const ESCO_PROJECT = {
  title: "Project ESCO",
  tagline: "Ethics, Sovereignty, and Coherence",
  dateRange: "2024 - Present",
  role: "Founder & Lead Architect",
  description:
    "A transparent, auditable AI safeguard framework. ESCO integrates a neuro-symbolic architecture that decouples the neural core from a deterministic Symbolic Ethics Layer. It maintains coherence and delivers truth in a user-chosen tone.",
  subProjects: [
    {
      title: "Neuro-Symbolic Safeguard & Ethics Gate",
      description: "Hybrid AI framework with deterministic symbolic constraints.",
    },
    {
      title: "Forensic Probing & Adversarial Research",
      description: "Adversarial testing on frontier models (GPT-4o, Claude 3.5) to identify deceptive alignment.",
    },
    {
      title: "Audit & Transparency Layer",
      description: "Reasoning Trace Graphs and Immutable Decision Logs for forensic review.",
    },
  ],
  figmaBoards: [
    {
      label: "Layered Architecture Map",
      href: "https://www.figma.com/board/5mJ6fDzeAvRiH5VqXz6PCT/ESCO-Layered-Architecture-Map",
      img: "/images/esco-layered-architecture.png",
    },
    {
      label: "Cross-Domain Network",
      href: "https://www.figma.com/board/ytQZnXTlbivQE67RyA4h5m/ESCO-Cross-Domain-Architecture-Network",
      img: "/images/esco-cross-domain-architecture.png",
    },
    {
      label: "System Architecture",
      href: "https://www.figma.com/board/N88czdXX6gDNbkP5c01Lq3/ESCO-System-Architecture-Map",
      img: "/images/esco-system-architecture.png",
    },
    {
      label: "SocraBot Fallacy Model",
      href: "https://www.figma.com/board/THRCAnzSeMAOIDTSQA92jJ/SocraBot-Fallacy-Accumulation-Scoring-Model",
      img: "/images/socrabot-fallacy-model.png",
    },
  ],
  tags: ["Neuro-Symbolic AI", "Ethics", "Adversarial Research", "Transparency"],
};

export const ECOSYSTEM_PROJECTS = [
  {
    title: "SocraBot",
    tagline: "Socratic AI for dialectical conversation",
    description: "A real-time monitoring framework built around a Fallacy Accumulation Scoring Model. Employs reinforcement-tuned logic/fallacy detection to surface sycophancy, reward-hacking, and rhetorical manipulation in live AI conversations.",
    tags: ["Dialectic AI", "Fallacy Detection", "RL"],
    link: "https://www.figma.com/board/THRCAnzSeMAOIDTSQA92jJ/SocraBot-Fallacy-Accumulation-Scoring-Model",
  },
  {
    title: "Light Web",
    tagline: "An ethical alternative digital space",
    description: "Ad-free, community-oriented platform with chatrooms and embedded ethical AIs. Multi-agent system with sentiment analysis for moderation.",
    tags: ["Decentralized Web", "Multi-Agent"],
    link: null,
  },
  {
    title: "MedBot",
    tagline: "Medical research bias detector",
    description: "Multi-layer NLP pipeline that ingests and grades medical studies for bias and methodological rigor by recursively analyzing citations.",
    tags: ["NLP", "Bias Detection", "Citation Analysis"],
    link: null,
  },
  {
    title: "BillBot",
    tagline: "Government bill transparency analyzer",
    description: "Analyzes legislation for incoherence, hidden agendas, or contradictions between bill titles and contents using Transformer-based semantic contrastive analysis.",
    tags: ["Legal NLP", "Transparency"],
    link: null,
  },
  {
    title: "ArchiveBot (DeepFile)",
    tagline: "Declassified document intelligence",
    description: "Parses and analyzes FOIA files. Downloads, OCRs, and semantically maps entities across documents, highlighting contradictions.",
    tags: ["Document Intelligence", "FOIA"],
    link: null,
  },
];
